* Strategic Practice
** 1 Naive Definition of Probability
1. For each part decide whether the blank should be filled with =, < or >
and give a short but clear explanation.

(a) (probability that the total after rolling 4 fair dice is 21) (probability that
the total after rolling 4 fair dice is 22)

Here we have a > relationship. 4 dice can sum up to 24, so for it to
sum 21 some dice must have lower number than 6. In fact, the dice that
are not 6 should total 3 amongst all of them in their difference with
6. For 22 they need to total 2, so already there's a lower number of
combinations and the numerator will be smaller.

#+BEGIN_SRC python :results output
import random

twenty_ones = 0
twenty_twos = 0
dice = list(range(1, 7))

for i in range(10000000):
    res = sum(random.choice(dice) for _ in range(4))
    if res == 21:
        twenty_ones += 1
    elif res == 22:
        twenty_twos += 1

print('{} 21s vs {} 22s'.format(twenty_ones, twenty_twos))
#+END_SRC

#+RESULTS:
: 153840 21s vs 77226 22s


(b) (probability that a random 2 letter word is a palindrome1) (probability that
a random 3 letter word is a palindrome)

The same, since the "endpoints" will always have to be the same
letter, the middle letter for the 3 letter word case does not affect
the probability at all.


2. A random 5 card poker hand is dealt from a standard deck of cards. Find the
probability of each of the following (in terms of binomial coecients).

(a) A flush (all 5 cards being of the same suit; do not count a royal
flush, which is a flush with an Ace, King, Queen, Jack, and 10)

#+BEGIN_SRC 
4 x (13 choose 5) - 4
------------------------
     52 choose 5
#+END_SRC

(b) Two pair (e.g., two 3’s, two 7’s, and an Ace)

#+BEGIN_SRC 
12 x (4 choose 2) + 11 x (4 choose 2) x 4
-----------------------------------------
            52 choose 5
#+END_SRC

My mistake here was that I misunderstood and thought we would always
have to have an ace. This is not the case, it can be any card (that is
not already in one of the pairs of course). So the real answer is:

#+BEGIN_SRC 
(13 choose 2) x (4 choose 2)^2 x 44
-----------------------------------
         52 choose 5
#+END_SRC


3. (a) How many paths are there from the point (0, 0) to the point (110, 111) in
the plane such that each step either consists of going one unit up or one unit to the
right?

In the end 110 steps have to be taken to the right and 111 up at some
point. We can choose at what steps we go right, and then the steps we
go up are determined.

221 choose 110

(b) How many paths are there from (0, 0) to (210, 211), where each step consists of
going one unit up or one unit to the right, and the path has to go through (110, 111)?

Since it's always advancing we can't go left or down, we first have to
make our way to (110, 111) which is the previous answer. Then for each
of those ways we have to move 100 right and 100 up, we can employ the
same logic as before.

(221 choose 110) x (200 choose 100)

4. A norepeatword is a sequence of at least one (and possibly all) of
   the usual 26 letters a,b,c,. . . ,z, with repetitions not
   allowed. For example, “course” is a norepeatword, but “statistics”
   is not. Order matters, e.g., “course” is not the same as “source”.

A norepeatword is chosen randomly, with all norepeatwords equally likely. Show
that the probability that it uses all 26 letters is very close to 1/e.


The different number of ways we can permute 26 letters is 26!. The
total number of norepeat words is 26! + 26 x 25 x 23 x ... x 3 + 26 x 25 x 23 x ... x 4 + ... + 26
which is the same as

#+BEGIN_SRC 
26!   26!   26!         26!
--- + --- + --- + ... + ---
1!    2!    3!          25!
#+END_SRC

this is the same as

#+BEGIN_SRC 
    (  1     1     1           1  )
26! | --- + --- + --- + ... + --- |
    (  1!    2!    3!         25! )
#+END_SRC

which is approximately

26!e

So the ratio of 26 norepeat words to all possible no repeat words is

#+BEGIN_SRC 
26!                      1
---- which approximates  -
26!e                     e
#+END_SRC

** 2 Story Proofs
5. Give a story proof that \sum_{k=0}^n n \choose k = 2^n.
   
Think of n being elements of a set. Think of k as how many ways we can
make subsets of size k from the set. Since k goes from 0 (1 way the
empty set) to n (1 way the original set itself). Then we will have
counted all possible subsets. And the number of possible subsets of a
set of cardinality n is 2^n.
   

6. Give a story proof that

#+BEGIN_SRC 
 (2n)!
-------- = (2n - 1)(2n - 3)...3*1
2^n * n!
#+END_SRC

I couldn't get this at all. The posted answer says to think of taking
2n people and counting how many ways there are to form n partnerships.
We can line them up in a row (randomly ordered) and say the first two
are a pair, the second two are pair to, etc. This is said to overcount
by 2^n * n!. Which I'm struglling with but I'll accept for now. The
right side now makes more sense, we randomly choose the first person,
then there are (2n-1) choices for their partner, then we choose
another person randomly from the remaining then there are (2n-3)
persons to be their partner, etc.


7. Show that for all positive integers n and k with n >= k

n \choose k + n \choose (k - 1) = (n+1) \choose k


Algebraic proof:

#+BEGIN_SRC 
  n!            n!             (n+1)!
------   + -------------- = -------------
k!(n-k)!   (k-1)!(n-k+1)!    k!(n+1-k)!


   n!(n-k+1)! + n!k            (n+1)!
------------------------- = -------------
    k!(n-k+1)!                k!(n-k+1)!



n!(n-k+1)! + n!k = (n+1)!

n!n -n!k + n! + n!k = (n+1)!

n!n + n! = (n+1)!

(n + 1)n! = (n+1)! which is true by definition of factorial
#+END_SRC


For the story proof, let's think of the left hand side as the number
of ways of choosing groups of size k without the designated president
or groups of size k-1 with the designated president (which when
account for makes the group of size k) too. The right hand side is
just that, of a population of n plus the president, it counts how many
groups of k we can make, some of them will contain the president and
some will not.

* Homework 1
1. A certain family has 6 children, consisting of 3 boys and 3
   girls. Assuming that all birth orders are equally likely, what is
   the probability that the 3 eldest children are the 3 girls.
   

Let's label the children m1, m2, m3, f1, f2, f3 (m for male, f for
female). The total number of possible birth orders is 6!. There are 3!
ways to order the three males first, and 3! ways to order the three
females.

#+BEGIN_SRC 
                                         (3!)^2
P(Eldest 3 children are the 3 girls) = ---------- = 0.05 
                                           6!
#+END_SRC


2. (a) How many ways are there to split a dozen people into 3 teams, where
   one team has 2 people and the other 2 teams have 5 people each.

We can first choose the team of 2 people (12 choose 2). Then we are
left with 10 people, we choose 5 to make one team (10 choose 5) and
the other team is composed the ones that are left. But this over
counts by 2. So the final answer is

#+BEGIN_SRC 
(12 choose 2)(10 choose 5)
--------------------------
            2
#+END_SRC

   (b) How many ways are there to split a dozen people into 3 teams,
   where each team has 4 people?
   
We can choose the first team of 4 people (12 choose 4), then we choose
other 4 for the second team (8 choose 4) and the rest are the third
team. This second selection has the same issue as the one in (a), it
overcounts by a factor of 2.

#+BEGIN_SRC 
(12 choose 4)(8 choose 4)
--------------------------
            2
#+END_SRC

3. A college has 10 (non-overlapping) time slots for its courses, and
   blithely assigns courses to time slots randomly and independetly. A
   student randomly chooses 3 of the courses to enroll in (for the
   PTP, to avoid getting fined). What is the probability that there is
   a conflict in the student's schedule?
   
So there are 2 aspects to this question. How the college assigned the
courses, and which courses the student picks. We know tha the student
has chosen 3 randomly, now the question is what is the probability
that the college had scheduled at least 2 of those 3 courses during
the same time slot. Since the 3 courses are independently assigned
time slots and with equal probability, there are 10^3 ways for the
courses to be assigned to time slots, but only (10)(9)(8) for them to
not overlap.

#+BEGIN_SRC
      10(9)(8)
--------------------- = 0.72
       10^3
#+END_SRC

Which is the probability of no conflict, so the probability of a
conflict is 0.28.

4. A city with 6 districts has 6 robberies in a particular
   week. Assume the robberies are located randomly, with all
   possibilities for which robbery occurred where equally likely. What
   is the probability that some district had more than 1 robbery?
   

Robberies can repeat in a district (so I'm already thinking replacement).

Number of ways to arrange robbery without repeating district = 6!
Number of ways to arrange robbery while possibly repeating district = 6^6

P(Some district more than 1 robbery) = 1 - P(Robberies all in different districts)

#+BEGIN_SRC 
P(Robberies all in different districts) = 6! / (6^36) = 0.0154320987654
P(Some district more than 1 robbery) = 1 - (6! / (6^36)) = 0.984567901235
#+END_SRC

5. Elk dwell in a certain forest. There are N elk, of which a simple
   random sample of size n are captured and tagged ("simple random
   sample" means that all (N choose n) sets of elk are equally
   likely). The captured elk are returned to the population and then a
   new sample is drawn, this time with size m. This is an important
   method which is widely-used in ecology, known as capture-recapture.
   
What is the probability that exactly k of the m elk in the new sample
were previously tagged? (Assume that an elk that was captured before
doesn't become more or less likely to be captured again).

After the first capture, n elks will be tagged, and N - n elks will
not be tagged. In the second captured, we are interested on the
probability that k were previously tagged, and M - k not tagged. So there
is some reation between k and n, and between N - n and m - k.

We can think of the number of ways to arrange groups of k out of the n
elks that were previously tagged. This is the number of instances
where it happens that k of the m elks chosen in the second round were
already tagged.

Let's think of labeling the elks. For example for N = 5 we have elks

1 2 3 4 5

And let's think of also labeling in the second round as
N+first_round_label

So we have

6 7 8 9 10

Then if we have for example n = 3, m = 3, k = 2

We choose (n + m) out of our "extended" sample space.

So we choose 6 out {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

Say we pick {1, 6, 2, 8, 3, 10}

Here elk 1 (which is the same as elk 6) was tagged and chosen again.
Same thing for elk 2 (which is the same as 8). Then elk 3 was chosen
in the first round but not in the second, elk 5 was chosen instead in
this round.

#+BEGIN_SRC 
     (n choose k)(N - n choose m - k)
--------------------------------------
         (2N choose n+m)
#+END_SRC

6. A jar contains r red balls and g green balls, where r and g are
   fixed positive integers. A ball is drawn from the jar randomly
   (with all possibilities equally likely), and then a second ball is
   drawn randomly.

(a) Explain intuitively why the probability of the second ball being
green is the same as the probability of the first ball being green.

Because if the first draw was green, for the second draw there is less
probability of it being green. But if the first draw was not green,
then the second draw has more probability of being green, so it kind
of evens out.

(b) Define notation for the sample space of the problem, and use this
to compute the probabilities from (a) and show that they are the same.

#+BEGIN_SRC 
P(G1) = g/(r + g)
P(G2) = P(G1)(g-1)/(r+g-1) + (1-P(G1))(g)/(r+g-1)
         g  g-1       r   g       g(g-1) + rg      g(r+g-1)       g
P(G2) = --- ------ + --- ----- = -------------- = ------------ = ----
        r+g r+g-1    r+g r+g-1    (r+g)(r+g-1)    (r+g)(r+g-1)   (r+g)
#+END_SRC

(c) Suppose that there are 16 balls in total, and that the probability
that the two balls are the same color is the same as the probability
they are different colors. What are r and g (list all possibilities)?

r = g = 8

7. (a) Show a story proof using that ...

where n and k are positive integers with n >= k

Hint: Imagine arranging a troup of people by age, and then think about
the oldest person in each subgroup.
